### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by robertreems** [cerealkella/rest-uploader#3]
Hi Justin,

As someone who can't contribute to open source code (yet), I just want to say thank you for the rest-uploader! I've been using Joplin to replace OneNote. And I've been using the rest-uploader for several months now. I'm using it to archive paper letters for my personal archive. 

So again thank you!

Robert

**Comment by cerealkella** [comment]
Robert -
Thanks for the feedback - I appreciate it, and I'm very happy to hear it's working for you!
