### ISSUE TITLE
Integrating into NextCloud Snap Package

### ISSUE THREAD

**Issue by dougleclair** [cerealkella/rest-uploader#7]
Hi kellerjustin,

I was wondering if it was possible to install rest-uploader inside a NextCloud Snap package? And if so do you have any advice on how to do it?

Thanks in advance, and thank you for your work on this project!
Best regards,
Doug

**Comment by cerealkella** [comment]
Doug, thanks for the inquiry. Unfortunately I am not sure how to go about accomplishing this. If you endeavor to try and have any luck, please let me know!
Thanks!
